"angularjs":
  aliases:
    - "angular js"
    - "angular.js"
"cyber security":
  aliases:
    - "cybersecurity"
"hp-unix":
  aliases:
    - "hp unix"
"html5":
  aliases:
    - "html 5"
"javascript":
  aliases:
    - "java script"
"mongodb":
  aliases:
    - "mongo db"
"ms sql server":
  aliases:
    - "mssql server"
"mssql":
  aliases:
    - "ms sql"
"nodejs":
  aliases:
    - "node.js"
"oracle 11gr2":
  aliases:
    - "oracle 11g r2"
"oracle 11gr2 rac":
  aliases:
    - "oracle 11g r2 rac"
"oracle data guard":
  aliases:
    - "oracle dataguard"
"oracle goldengate":
  aliases:
    - "oracle golden gate"
"pl/sql":
  aliases:
    - "pl sql"
    - "plsql"
"red hat linux":
  aliases:
    - "redhat linux"
"sql plus":
  aliases:
    - "sqlplus"
"sql server":
  aliases:
    - "sqlserver"
"sql trace":
  aliases:
    - "sqltrace"
"t-sql":
  aliases:
    - "tsql"
"transact-sql":
  aliases:
    - "transact sql"
"unix shell scripts":
  aliases:
    - "unix/shell scripts"
