"""Ingestion submodules."""

from .constants import (
    EMBEDDING_TEXT_VERSION,
    EXPERIENCE_YEARS_METHOD,
    NORMALIZATION_VERSION,
    PARSING_VERSION_STRUCTURED,
    PARSING_VERSION_TEMPLATE,
    TAXONOMY_VERSION,
)

__all__ = [
    "EMBEDDING_TEXT_VERSION",
    "EXPERIENCE_YEARS_METHOD",
    "NORMALIZATION_VERSION",
    "PARSING_VERSION_STRUCTURED",
    "PARSING_VERSION_TEMPLATE",
    "TAXONOMY_VERSION",
]
